# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source ‘https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git’
source ‘https://github.com/CocoaPods/Specs.git’
target 'xlqp-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xlqp-desktop

end

target 'xlqp-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xlqp-mobile
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'UMCCommon'
  pod 'UMCPush'
  pod 'UMCSecurityPlugins'	
end
